In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
'''
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session
'''

In [2]:
file_path = r"C:\Users\rinka\Downloads\archive\electronics_product.csv"
df= pd.read_csv(file_path)

In [3]:
df.drop(columns=['Unnamed: 0', 'image', 'link'], inplace=True)

In [4]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,4.0,965,"₹10,999","₹18,999"
1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,4.3,"113,956","₹18,999","₹19,999"
2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,4.2,"90,304","₹1,999","₹2,299"
3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,4.1,"24,863","₹15,999","₹24,999"
4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,4.3,"113,956","₹18,999","₹19,999"

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9600 entries, 0 to 9599
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            9600 non-null   object
 1   main_category   9600 non-null   object
 2   sub_category    9600 non-null   object
 3   ratings         9505 non-null   object
 4   no_of_ratings   9505 non-null   object
 5   discount_price  9116 non-null   object
 6   actual_price    9530 non-null   object
dtypes: object(7)
memory usage: 525.1+ KB

In [6]:
df.shape

(9600, 7)

In [7]:
df.duplicated().sum()

563

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.isnull().sum()

name                0
main_category       0
sub_category        0
ratings            92
no_of_ratings      92
discount_price    473
actual_price       70
dtype: int64

In [11]:
df['ratings'] = pd.to_numeric(df['ratings'], errors='coerce')

In [12]:
df['no_of_ratings'] = pd.to_numeric(df['no_of_ratings'], errors='coerce')

In [13]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,4.0,965.0,"₹10,999","₹18,999"
1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,4.3,NaN,"₹18,999","₹19,999"
2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,4.2,NaN,"₹1,999","₹2,299"
3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,4.1,NaN,"₹15,999","₹24,999"
4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,4.3,NaN,"₹18,999","₹19,999"

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9037 entries, 0 to 9599
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            9037 non-null   object
 1   main_category   9037 non-null   object
 2   sub_category    9037 non-null   object
 3   ratings         8927 non-null   float64
 4   no_of_ratings   4270 non-null   float64
 5   discount_price  8564 non-null   object
 6   actual_price    8967 non-null   object
dtypes: float64(2), object(5)
memory usage: 564.8+ KB

In [15]:
df.isna().sum()

name                 0
main_category        0
sub_category         0
ratings            110
no_of_ratings     4767
discount_price     473
actual_price        70
dtype: int64

In [16]:
df['main_category'].unique()

array(['tv, audio & cameras'], dtype=object)